markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Akax`s Blog
url: http://blog.uytor.info
subscribe: http://feeds.feedburner.com/akax
exclude: [ README.md, newpost.rb ]
domain: blog.uytor.info
author: Akax Uyghur
email: akax001@gmail.com
auto: true
twitterID: akax001
googleAnalyticsID: UA-5531632-1
disqusShortname: akax